// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLl3erDC8Xrt-dPXUyAwlW_KV-ESEi4s4',
    appId: '1:760056943614:web:a28e9419ba2306fbe9a6af',
    messagingSenderId: '760056943614',
    projectId: 'ies-miravent-trabajos',
    authDomain: 'ies-miravent-trabajos.firebaseapp.com',
    storageBucket: 'ies-miravent-trabajos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLJFHaL9XwUv6BxemHmAg9sLXl6mZ0KUE',
    appId: '1:760056943614:android:7dddc1ec2ec6e95ae9a6af',
    messagingSenderId: '760056943614',
    projectId: 'ies-miravent-trabajos',
    storageBucket: 'ies-miravent-trabajos.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACpcSQwTgEfaRnLW3c7QOr28mpnN3odeI',
    appId: '1:760056943614:ios:d48ad05ad2f161b6e9a6af',
    messagingSenderId: '760056943614',
    projectId: 'ies-miravent-trabajos',
    storageBucket: 'ies-miravent-trabajos.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpcSQwTgEfaRnLW3c7QOr28mpnN3odeI',
    appId: '1:760056943614:ios:d48ad05ad2f161b6e9a6af',
    messagingSenderId: '760056943614',
    projectId: 'ies-miravent-trabajos',
    storageBucket: 'ies-miravent-trabajos.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLl3erDC8Xrt-dPXUyAwlW_KV-ESEi4s4',
    appId: '1:760056943614:web:fa936628e517e2cbe9a6af',
    messagingSenderId: '760056943614',
    projectId: 'ies-miravent-trabajos',
    authDomain: 'ies-miravent-trabajos.firebaseapp.com',
    storageBucket: 'ies-miravent-trabajos.firebasestorage.app',
  );

}